# Generated by Django 4.2.1 on 2023-05-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Post',
        ),
    ]
